# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 67990ecfc96fc50b02a946b9d3bb820423a721693634a55d401779b0e0b32012b619cbb359b4a4a48bdeccc28304d77665faeba6d55ae7dda1682c5d766a6f82

test:
  secret_key_base: e6b9f0a7dc7eec17f565df30f86dbfc921b0a1e1cca6dbc861fd6152b9a887f5b361b6db2fc6275733a0929b717daaca2ab3eb0b1fca0dab357c3fe0e62d0331

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
